### Get app
GET localhost:8080

### AUTH ###
### Sign Up
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "123456"
}

### Index
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

### Form
POST localhost:8080/form/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTMwYmM5ZGYtMmQ2Yi00YmE5LWI1MGItNWQ3NmI0M2RiOWZlIiwiaWF0IjoxNjcwNDQwMTkwLCJleHAiOjE2NzA0NDE5OTAsImlzcyI6ImZzX2NoYWxsZW5nZV9hcGkifQ.NwBeYJQ7w92V2ZiTCMyA_SlddC8LJx4LtLz9IEHplUI

{
  "form_name": "Test Form",
  "form_content": "Test Content"
}

### Get all user's form
GET localhost:8080/form/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTMwYmM5ZGYtMmQ2Yi00YmE5LWI1MGItNWQ3NmI0M2RiOWZlIiwiaWF0IjoxNjcwNDQ0NDAzLCJleHAiOjE2NzA0NDYyMDMsImlzcyI6ImZzX2NoYWxsZW5nZV9hcGkifQ.FCC0OyW_morHYz3TPhnpXuFaKPyepo_p_4KZ5JFquG4



